export interface MenuItem {
  id: string;
  name: string;
  description: string;
  /** Per-item image, overrides the section's shared/fallback image when set. */
  image?: string;
  price?: number;
  rating?: number;
  ratingCount?: string;
  /** Size options badge shown on the card, e.g. "Regular | Large". */
  sizeLabel?: string;
}

export interface MenuSection {
  id: string;
  title: string;
  items: MenuItem[];
}

export const brandMenus: Record<string, MenuSection[]> = {
  mrbeast: [
    {
      id: "combos",
      title: "Combos",
      items: [
        {
          id: "beast-style-burger-combo",
          name: "Beast Style Burger Combo",
          description:
            "Smashed crispy beef patties with Holor seasoning, American cheese, pickles, diced onion, mayo, ketchup and mustard on a toasted bun, served with your choice of crinkle fries and a drink.",
          image: "/images/menu/mr-beast/beast-style-burger-combo.jpg",
          price: 0,
          rating: 4.9,
          ratingCount: "10K+",
        },
        {
          id: "chicken-sandwich-combo",
          name: "Chicken Sandwich Combo",
          description:
            "A crispy chicken tender sandwich or Nashville hot chicken tender sandwich with your choice of crinkle fries, Beast Style fries and a drink.",
          image: "/images/menu/mr-beast/chicken-sandwich-combo.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "burgers",
      title: "Burgers",
      items: [
        {
          id: "beast-style",
          name: "Beast Style",
          description:
            "Smashed crispy beef patties with Holor seasoning, American cheese, pickles, diced onion, mayo, ketchup and mustard on a toasted bun.",
          image: "/images/menu/mr-beast/beast-style.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "chandler-style",
          name: "Chandler Style",
          description:
            "Two smashed crispy beef patties with house seasoning, served with American cheese on a toasted bun.",
          image: "/images/menu/mr-beast/chandler-style.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "nolan-style",
          name: "Nolan Style",
          description:
            "Two smashed crispy beef patties with house seasoning, American cheese, bacon, topped with crinkle fries on a toasted bun.",
          image: "/images/menu/mr-beast/nolan-style.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "karls-deluxe",
          name: "Karl's Deluxe",
          description:
            "A patty melt styled Karl's style with a crispy seasoned beef patty, caramelized onions and cheese on a toasted inverted bun.",
          image: "/images/menu/mr-beast/karls-deluxe.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "sandwiches",
      title: "Sandwiches",
      items: [
        {
          id: "karls-grilled-cheese",
          name: "Karl's Grilled Cheese",
          description: "3 slices of American cheese griddled crisp on an inverted bun.",
          image: "/images/menu/mr-beast/karls-grilled-cheese.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "crispy-chicken-tender-sandwich",
          name: "Crispy Chicken Tender Sandwich",
          description: "With mayo, shredded lettuce and pickles on a toasted bun.",
          image: "/images/menu/mr-beast/crispy-chicken-tender-sandwich.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "nashville-hot-chicken-tender-sandwich",
          name: "Nashville Hot Chicken Tender Sandwich",
          description:
            "Two smashed crispy beef patties with house seasoning, American cheese, bacon, topped with crinkle fries on a toasted bun.",
          image: "/images/menu/mr-beast/nashville-hot-chicken-tender-sandwich.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "sides",
      title: "Sides",
      items: [
        {
          id: "crinkle-fries",
          name: "Crinkle Fries",
          description: "Crinkle fries lightly seasoned with salt.",
          image: "/images/menu/mr-beast/crinkle-fries.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "signature-crinkle-fries",
          name: "Signature Crinkle Fries",
          description: "Crinkle fries seasoned with spicy red pepper, garlic, paprika, sugar and a hint of lime.",
          image: "/images/menu/mr-beast/signature-crinkle-fries.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "beast-style-fries",
          name: "Beast Style Fries",
          description:
            "Seasoned crinkle fries loaded with caramelized onions, American cheese, pickles, mayo, ketchup and mustard.",
          image: "/images/menu/mr-beast/beast-style-fries.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "desserts",
      title: "Desserts",
      items: [
        {
          id: "chocolate-chip-cookie",
          name: "Chocolate Chip Cookie",
          description: "Freshly baked chocolate chip cookie.",
          image: "/images/menu/mr-beast/chocolate-chip-cookie.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "beverages",
      title: "Beverages",
      items: [
        {
          id: "canned-soda",
          name: "Canned Soda",
          description: "Ice-cold canned soda of your choice.",
          image: "/images/menu/mr-beast/canned-soda.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "bottled-water",
          name: "Bottled Water",
          description: "Chilled bottled water.",
          image: "/images/menu/mr-beast/bottled-water.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
  ],

  cpk: [
    {
      id: "cpk-original-pizza",
      title: "CPK Original Pizza",
      items: [
        {
          id: "the-original-bbq-chicken-pizza",
          name: "The Original BBQ Chicken Pizza",
          description:
            "Created Here In 1985. Our Legendary BBQ Sauce, Grilled Chicken, Smoked Gouda, Red Onions, And Fresh Cilantro Transform This Original To Iconic.",
          image: "/images/menu/california-pizza/the-original-bbq-chicken-pizza.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "wild-mushroom",
          name: "Wild Mushroom",
          description:
            "Shaved Cremini Mushrooms, Extra Virgin Olive Oil, Fresh Garlic, With Romano & Mozzarella, Slivered Scallions, And Cracked Black",
          image: "/images/menu/california-pizza/wild-mushroom.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "california-veggie",
          name: "California Veggie",
          description:
            "Broccolini, Grilled Zucchini, Shaved Cremini Mushrooms, Roasted Cherry Tomatoes, Corn, Red Onions, And Mozzarella.",
          image: "/images/menu/california-pizza/california-veggie.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "classic-pizzas",
      title: "Classic Pizzas",
      items: [
        {
          id: "the-works",
          name: "The Works",
          description:
            "Spicy Italian Sausage, Rustic Pepperoni, Cremini Mushrooms, Mozzarella, Red Onions, Green Peppers, Olives, And Wild Greek Oregano.",
          image: "/images/menu/california-pizza/the-works.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "mushroom-pepperoni-sausage",
          name: "Mushroom Pepperoni Sausage",
          description:
            "Cremini Mushrooms, Rustic Pepperoni, Spicy Italian Sausage, Fresh Torn Basil, Mozzarella And Wild Greek Oregano.",
          image: "/images/menu/california-pizza/mushroom-pepperoni-sausage.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "five-cheese-fresh-tomato",
          name: "Five Cheese + Fresh Tomato",
          description: "Fresh And Traditional Mozzarella, Monterey Jack, Smoked Gouda, And Romano With Tomato And Fresh Basil.",
          image: "/images/menu/california-pizza/five-cheese-fresh-tomato.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "neapolitan-burrata",
          name: "Neapolitan Burrata",
          description:
            "Our Housemade Neapolitan Pizza Sauce, Slow-Roasted Cherry Tomatoes, And Parmesan with Creamy Burrata, Extra Virgin Olive Oil, And Fresh Basil.",
          image: "/images/menu/california-pizza/neapolitan-burrata.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "pepperoni",
          name: "Pepperoni",
          description: "Rustic And Spicy Pepperoni With Fresh Mozzarella And Wild Greek Oregano.",
          image: "/images/menu/california-pizza/pepperoni.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "hawaiian",
          name: "Hawaiian",
          description: "Fresh Pineapple, Applewood Smoked Ham, And Slivered Scallions.",
          image: "/images/menu/california-pizza/hawaiian.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "margherita",
          name: "Margherita",
          description: "Italian Tomatoes With Fresh Mozzarella, Fresh Basil, And Parmesan. Made Best On Crispy Thin Crust.",
          image: "/images/menu/california-pizza/margherita.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "globally-inspired",
      title: "Globally Inspired",
      items: [
        {
          id: "sicilian",
          name: "Sicilian",
          description:
            "Spicy Marinara, Italian Sausage, Capicola Ham, Pepperoni, Mozzarella, Shaved Parmesan, Fresh Basil, And Wild Greek Oregano. Made Best On Crispy Thin Crust.",
          image: "/images/menu/california-pizza/sicilian.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "spicy-chipotle-chicken-pizza",
          name: "Spicy Chipotle Chicken Pizza",
          description:
            "Chipotle Adobo Sauce, Grilled Chicken, Shaved Poblanos Queso Quesadilla And Monterey Jack Cheeses With Housemade Roasted Corn & Black Bean Salsa, Fresh Cilantro, And Tangy Lime Crema.",
          image: "/images/menu/california-pizza/spicy-chipotle-chicken-pizza.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "tostada-pizza",
          name: "Tostada Pizza",
          description:
            "Crisp Lettuce, Tortilla Strips, Scallions, Housemade Herb Ranch, And Roasted Tomato Salsa Top This Crispy Thin Crust With Layers Of Black Beans, Queso Quesadilla And Monterey Jack Cheeses.",
          image: "/images/menu/california-pizza/tostada-pizza.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "sicilian-2",
          name: "Sicilian",
          description:
            "Spicy Marinara, Italian Sausage, Capicola Ham, Pepperoni, Mozzarella, Shaved Parmesan, Fresh Basil, And Wild Greek Oregano. Made Best On Crispy Thin Crust.",
          image: "/images/menu/california-pizza/sicilian1.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
  ],

  cheesecake: [
    {
      id: "desserts",
      title: "Desserts",
      items: [
        {
          id: "brownie-crunch-choc-a-lot-cheesecake",
          name: "Brownie Crunch Choc-A-Lot Cheesecake",
          description: "Milk and White Chocolate Marbled Cheesecake on a Crunchy Toffee Brownie",
          image: "/images/menu/chees-cake/Browniecrunch-choc-a-Lot-cheesecake.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "original-cheesecake",
          name: "Original",
          description: "The One that Started it All! Our Famous Creamy Cheesecake with a Graham Cracker Crust and Sour Cream Topping",
          image: "/images/menu/chees-cake/Cheesecake-original.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "fresh-strawberry",
          name: "Fresh Strawberry",
          description: "The Original Topped with Glazed Fresh Strawberries. Our Most Popular Flavor for over 45 Years!",
          image: "/images/menu/chees-cake/fresh-strawberry.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "oreo-dream-extreme-cheesecake",
          name: "Oreo® Dream Extreme Cheesecake",
          description: "Creamy Cheesecake Layered with Oreo® Cookies, Topped with Oreo® Cookie Mousse and Chocolate Icing",
          image: "/images/menu/chees-cake/oreo-dream-extreme-cheesecake.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "ultimate-red-velvet-cake-cheesecake",
          name: "Ultimate Red Velvet Cake Cheesecake™",
          description: "Layers of Red Velvet Cake and Cheesecake Covered in Cream Cheese Frosting. Finished with White Chocolate",
          image: "/images/menu/chees-cake/ultimate-red-velvet-cake-cheesecake.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "reeses-peanut-butter-chocolate-cake-cheesecake",
          name: "Reese's® Peanut Butter Chocolate Cake Cheesecake",
          description: "Reese's® Peanut Butter Cups in Our Original Cheesecake with Layers of Delicious Fudge Cake and Caramel",
          image: "/images/menu/chees-cake/reese’s-peanut Butter-chocolate-cake-cheesecake.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "godiva-chocolate-cheesecake",
          name: "Godiva® Chocolate Cheesecake",
          description: "Flourless Godiva® Chocolate Cake, Topped with Godiva® Chocolate Cheesecake and Chocolate Mousse",
          image: "/images/menu/chees-cake/godiva-chocolate-cheesecake.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "peach-perfect-with-raspberry-drizzle",
          name: "Peach Perfect with Raspberry Drizzle",
          description: "Peach Cheesecake Swirled with Peaches, Finished with Raspberry Sauce",
          image: "/images/menu/chees-cake/peach-perfect-with-raspberry-drizzle.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "coconut-cream-pie-cheesecake",
          name: "Coconut Cream Pie Cheesecake",
          description: "Coconut Cheesecake, Vanilla Custard and a Layer of Chocolate all on a Coconut Macaroon Crust",
          image: "/images/menu/chees-cake/coconut-cream-pie-cheesecake.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "adams-peanut-butter-cup-fudge-ripple",
          name: "Adam's Peanut Butter Cup Fudge Ripple",
          description: "Creamy Cheesecake Swirled with Caramel, Peanut Butter, Butterfingers® and Reese's Peanut Butter Cups",
          image: "/images/menu/chees-cake/adam’s-peanut-butter-cup-fudge-ripple.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "godiva-chocolate-cheesecake-2",
          name: "Godiva® Chocolate Cheesecake",
          description: "Flourless Godiva® Chocolate Cake, Topped with Godiva® Chocolate Cheesecake and Chocolate Mousse",
          image: "/images/menu/chees-cake/godiva-cream-cheesecake.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
  ],

  oneslice: [
    {
      id: "signature-slices",
      title: "Signature Slices",
      items: [
        {
          id: "cheese-slice",
          name: "Cheese Slice",
          description: "Melty five-cheese blend on our signature sauce and golden crust.",
          image: "/images/menu/one-more-slice/cheese-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "pepperoni-slice",
          name: "Pepperoni Slice",
          description: "Loaded edge-to-edge with crispy pepperoni over melted five-cheese blend.",
          image: "/images/menu/one-more-slice/pepperoni-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "sausage-slice",
          name: "Sausage Slice",
          description: "Savory Italian sausage crumbles over rich sauce and melted cheese.",
          image: "/images/menu/one-more-slice/sausage-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "meat-lover-slice",
          name: "Meat Lover Slice",
          description: "Pepperoni, Italian sausage, and smoky bacon piled on melted five-cheese blend.",
          image: "/images/menu/one-more-slice/meat-lover-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "bbq-chicken-slice",
          name: "BBQ Chicken Slice",
          description: "Grilled chicken and red onions on sweet & smoky BBQ sauce.",
          image: "/images/menu/one-more-slice/bbq-chicken-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "buffalo-ranch-slice",
          name: "Buffalo Ranch Slice",
          description: "Grilled chicken on spicy buffalo sauce, finished with a cool ranch drizzle.",
          image: "/images/menu/one-more-slice/buffalo-ranch-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "chicken-supreme-slice",
          name: "Chicken Supreme Slice",
          description: "Grilled chicken, mushrooms, bell peppers, and red onions on classic sauce.",
          image: "/images/menu/one-more-slice/chicken-supreme-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "veggie-slice",
          name: "Veggie Slice",
          description: "Red onions, green bell peppers, and mushrooms over bubbling cheese.",
          image: "/images/menu/one-more-slice/veggie-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "breakfast-slices",
      title: "Breakfast Slices",
      items: [
        {
          id: "egg-cheese-slice",
          name: "Egg & Cheese Slice",
          description: "Fluffy scrambled eggs over creamy cheddar sauce and five-cheese blend.",
          image: "/images/menu/one-more-slice/egg&cheese-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "egg-n-sausage-slice",
          name: "Egg N Sausage Slice",
          description: "Scrambled eggs and savory sausage crumbles over creamy cheddar sauce.",
          image: "/images/menu/one-more-slice/egg-sausage-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "egg-n-bacon-slice",
          name: "Egg N Bacon Slice",
          description: "Scrambled eggs and crispy bacon over creamy cheddar cheese sauce.",
          image: "/images/menu/one-more-slice/egg-bacon-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "sweet-slices",
      title: "Sweet Slices",
      items: [
        {
          id: "caramel-apple-slice",
          name: "Caramel Apple Slice",
          description: "Warm apple pie filling on cinnamon-sugar crust with cream cheese icing and caramel drizzle.",
          image: "/images/menu/one-more-slice/caramel-apple-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "churro-supreme-slice",
          name: "Churro Supreme Slice",
          description: "Caramelized cinnamon-sugar crust drizzled with cream cheese icing and caramel.",
          image: "/images/menu/one-more-slice/churro-supreme-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "chocolate-bliss-slice",
          name: "Chocolate Bliss Slice",
          description: "Warm chocolate hazelnut spread with toasted marshmallows, chocolate chips, and powdered sugar.",
          image: "/images/menu/one-more-slice/chocolate-bliss-slice.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "snacks-and-sides",
      title: "Snacks & Sides",
      items: [
        {
          id: "cheesy-garlic-dippers",
          name: "Cheesy Garlic Dippers",
          description: "Golden-baked cheesy garlic crust cut into 12 dippers, served with dipping sauce.",
          image: "/images/menu/one-more-slice/cheesy-garlic-dippers.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
  ],

  dogitup: [
    {
      id: "signature-dogs",
      title: "Signature Dogs",
      items: [
        {
          id: "classic-american",
          name: "Classic American",
          description: "100% All Beef Hot Dog, topped with Ketchup, Mustard and Relish.",
          image: "/images/menu/dog-it-up/classic-american.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "nashville-hot",
          name: "Nashville Hot",
          description: "100% All Beef Hot Dog, topped with Nashville Hot Sauce, Warm Cheddar Sauce and Pickles.",
          image: "/images/menu/dog-it-up/nashville-hot.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "kansas-city-smokehouse",
          name: "Kansas City Smokehouse",
          description: "100% All Beef Hot Dog, topped with Nashville Hot Sauce, Bacon, and Warm Cheddar Sauce.",
          image: "/images/menu/dog-it-up/kansas-city-smokehouse.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "midwest-mac-daddy",
          name: "Midwest Mac Daddy",
          description: "100% All Beef Hot Dog, topped with creamy Mac & Cheese, Warm Cheddar Sauce and Bacon.",
          image: "/images/menu/dog-it-up/midwest-mac-daddy.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "texas-chili-cheese",
          name: "Texas Chili Cheese",
          description: "100% All Beef Hot Dog, topped with No Bean Chili, Warm Cheddar Sauce and diced onions.",
          image: "/images/menu/dog-it-up/texas-chili-cheese.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "chicago-dog",
          name: "Chicago Dog",
          description:
            "A Windy City Classic loaded with Mustard, Diced Onions, Pickles, Tomato, Sweet Relish, and a Sport Pepper for a Bright, Tangy Bite in Every Mouthful.",
          image: "/images/menu/dog-it-up/chicago-dog.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "sides",
      title: "Sides",
      items: [
        {
          id: "crinkle-fries",
          name: "Crinkle Fries",
          description: "Extra ridges, extra crunch.",
          image: "/images/menu/dog-it-up/crinkle-fries.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
          sizeLabel: "Regular | Large",
        },
        {
          id: "onion-rings",
          name: "Onion Rings",
          description: "Golden rings with a crunch.",
          image: "/images/menu/dog-it-up/onion-rings.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
          sizeLabel: "Regular | Large",
        },
        {
          id: "frings",
          name: "Frings",
          description: "Fries and rings ended the rivalry.",
          image: "/images/menu/dog-it-up/frings.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
          sizeLabel: "Regular | Large",
        },
        {
          id: "mac-n-cheese",
          name: "Mac N Cheese",
          description: "Comfort food's greatest hit.",
          image: "/images/menu/dog-it-up/mac-n-cheese.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "loaded-chili-cheese-fries",
          name: "Loaded Chili Cheese Fries",
          description: "Crispy fries topped with No Bean Chili, Warm Cheddar Sauce, Bacon and diced Onion.",
          image: "/images/menu/dog-it-up/loaded-chili-cheese-fries.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "beverages",
      title: "Beverages",
      items: [
        {
          id: "lemonade",
          name: "Lemonade",
          description: "Sunshine, squeezed and iced.",
          image: "/images/menu/dog-it-up/lemonade.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
          sizeLabel: "Regular | Large",
        },
        {
          id: "strawberry-lemonade",
          name: "Strawberry Lemonade",
          description: "Lemonade's summer crush.",
          image: "/images/menu/dog-it-up/strawberry-lemonade.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
          sizeLabel: "Regular | Large",
        },
        {
          id: "cola-fizz",
          name: "Cola-Fizz",
          description: "Ice cold, endlessly fizzy.",
          image: "/images/menu/dog-it-up/cola-fizz.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "orange-fizz",
          name: "Orange Fizz",
          description: "Bold, bubbly and bright orange.",
          image: "/images/menu/dog-it-up/orange-fizz.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "lemon-lime-fizz",
          name: "Lemon-Lime Fizz",
          description: "Crisp citrus, straight off the tap.",
          image: "/images/menu/dog-it-up/lemon-lime-fizz.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
          sizeLabel: "Regular | Large",
        },
        {
          id: "bottled-water",
          name: "Bottled Water",
          description: "Pure, chilled, zero fuss.",
          image: "/images/menu/dog-it-up/bottled-water.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
          sizeLabel: "500ml",
        },
      ],
    },
  ],

  manvsfries: [
    {
      id: "fries",
      title: "Fries",
      items: [
        {
          id: "asada-fries",
          name: "Asada Fries",
          description:
            "Sometimes, it's good to be bad. Take for example hella crisp, delicious french fries, drizzled with savory toppings beloved by everyone, everywhere.",
          image: "/images/menu/menvsfries/asada-fries.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "burritos",
      title: "Burritos",
      items: [
        {
          id: "socal-burrito",
          name: "SoCal Burrito",
          description:
            "Hella big flour tortilla, carne asada vs pollo asado, Cheetos® Flamin' Hot®, straight-cut fries, cheese, sour cream, guacamole, secret sauce, side of queso.",
          image: "/images/menu/menvsfries/socal-burrito.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "norcal-burrito",
          name: "NorCal Burrito",
          description:
            "Hella big flour tortilla, carne asada vs pollo asado, straight-cut fries, cheese, sour cream, guacamole, secret sauce psst... yum.",
          image: "/images/menu/menvsfries/norcal-burrito.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "cali-crunch",
          name: "Cali Crunch",
          description:
            "Make yours lit add Cheetos® Flamin' Hot® chips! Hella big flour tortilla, carne asada vs pollo asado, crunchy tostada, lettuce, tomato, cheese, cilantro, onions, guacamole, spiked ranch.",
          image: "/images/menu/menvsfries/cali-crunch.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "cowgirl-burrito",
          name: "Cowgirl Burrito",
          description:
            "Y'all Sho'nuff ain't ready! Hella big flour tortilla, carne asada vs pollo asado, straight-cut fries, beer-battered onion rings, bacon, cheese, and smoky bbq sauce all wrapped up in a pretty package.",
          image: "/images/menu/menvsfries/cowgirl-burrito.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "hella-dilla",
          name: "Hella-Dilla",
          description:
            "Hella big flour tortilla, hella cheese, hella meat, hella fries, and hella sides (sour cream, guacamole, spiked ranch, queso) add Cheetos® Flamin' Hot® or Doritos® Flamin' Hot® chips.",
          image: "/images/menu/menvsfries/hella-dilla.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "cbr-burrito",
          name: "CBR Burrito",
          description:
            "Chicken, Bacon, Ranch wrapped in a hella big flour tortilla, straight-cut fries, cheese, and guacamole... perfect.",
          image: "/images/menu/menvsfries/cbr-burrito.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
    {
      id: "desserts",
      title: "Desserts",
      items: [
        {
          id: "omg-cookies",
          name: "OMG Cookies",
          description: "4 DOUBLE STUF OREO® cookies battered in krusteaz sweet cream mix, topped with powdered sugar, and a side of chocolate.",
          image: "/images/menu/menvsfries/omg-cookies.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
        {
          id: "man-vs-fried-cheesecake",
          name: "Man vs Fried Cheesecake",
          description:
            "I mean #obvi rich and creamy NYC style cheesecake, graham cracker crust, battered in krusteaz sweet cream mix, topped with powder sugar, and a side of chocolate.",
          image: "/images/menu/menvsfries/manvsfried-cheesecake.jpg",
          price: 0,
          rating: 4.8,
          ratingCount: "10K+",
        },
      ],
    },
  ],

};
